/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Campaign } from "./Campaign";

export { Campaign__factory } from "./factories/Campaign__factory";
